Catkin-ProjectName: llog
Description:
Author: Morten Kjaergaard <mkjargaard@willowgarage.com>
Maintainer: Morten Kjaergaard <mkjargaard@willowgarage.com>
Homepage:
Vcs-Git: git://github.com/mkjargaard/llog.git

Version: 0.0.1

Depends: catkin

Catkin-CopyrightType:
Catkin-DebRulesType:
